
// Generated by scripts/task6/build_vivado_pcie_y26_lane0_no_reset_oracle.tcl.
`timescale 1ns / 1ps

module pcie_7x_top_aximm_ypcb_480t (
  output      pci_exp_txp,
  output      pci_exp_txn,
  input       pci_exp_rxp,
  input       pci_exp_rxn,

  input       sys_clk_p,
  input       sys_clk_n,
  input       sys_rst_n,

  input       clk_50,
  output      [2:0] led
);

wire pcie_led_unused;

pcie_7x_top_aximm #(
    .NO_RESET(1),
    .ENABLE_GEN2(0),
    .GT_DEVICE("GTX"),
    .CFG_DEV_ID(16'h0480)
) pcie_7x_top_aximm_i (
  .pci_exp_txp(pci_exp_txp),
  .pci_exp_txn(pci_exp_txn),
  .pci_exp_rxp(pci_exp_rxp),
  .pci_exp_rxn(pci_exp_rxn),
  .sys_clk_p(sys_clk_p),
  .sys_clk_n(sys_clk_n),
  .sys_rst_n(sys_rst_n),
  .led({pcie_led_unused, led})
);

endmodule

