set src_root /home/roland/pcie_7x
set out_dir [file normalize artifacts/task6/vivado-pcie-y26-lane0-oracle]
set overlay_dir [file join $out_dir overlay]
file mkdir $overlay_dir

set top_overlay [file join $overlay_dir pcie_7x_top_aximm_ypcb_480t_y26.v]
set xdc_overlay [file join $overlay_dir pcie_7x_ypcb_k480t_y26_lane0.xdc]

set top_fh [open $top_overlay w]
puts $top_fh {
// Generated by scripts/task6/build_vivado_pcie_y26_lane0_oracle.tcl.
`timescale 1ns / 1ps

module pcie_7x_top_aximm_ypcb_480t (
  output      pci_exp_txp,
  output      pci_exp_txn,
  input       pci_exp_rxp,
  input       pci_exp_rxn,

  input       sys_clk_p,
  input       sys_clk_n,
  input       sys_rst_n,

  input       clk_50,
  output      [2:0] led
);

wire pcie_led_unused;

pcie_7x_top_aximm #(
    .NO_RESET(0),
    .ENABLE_GEN2(0),
    .GT_DEVICE("GTX"),
    .CFG_DEV_ID(16'h0480)
) pcie_7x_top_aximm_i (
  .pci_exp_txp(pci_exp_txp),
  .pci_exp_txn(pci_exp_txn),
  .pci_exp_rxp(pci_exp_rxp),
  .pci_exp_rxn(pci_exp_rxn),
  .sys_clk_p(sys_clk_p),
  .sys_clk_n(sys_clk_n),
  .sys_rst_n(sys_rst_n),
  .led({pcie_led_unused, led})
);

endmodule
}
close $top_fh

set xdc_fh [open $xdc_overlay w]
puts $xdc_fh {
# YPCB PCIe Gen1 oracle: external PERST# on board-file Y26 and Vivado systest lane-0 placement.

set_property PACKAGE_PIN J8 [get_ports {sys_clk_p}]
set_property PACKAGE_PIN J7 [get_ports {sys_clk_n}]

set_property PACKAGE_PIN H6 [get_ports {pci_exp_rxp}]
set_property PACKAGE_PIN H5 [get_ports {pci_exp_rxn}]
set_property PACKAGE_PIN F2 [get_ports {pci_exp_txp}]
set_property PACKAGE_PIN F1 [get_ports {pci_exp_txn}]

set_property PACKAGE_PIN Y26 [get_ports {sys_rst_n}]
set_property PULLUP true [get_ports {sys_rst_n}]
set_property IOSTANDARD LVCMOS18 [get_ports {sys_rst_n}]

set_property PACKAGE_PIN AA28 [get_ports {clk_50}]
set_property IOSTANDARD LVCMOS18 [get_ports {clk_50}]

set_property PACKAGE_PIN N30 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
set_property PACKAGE_PIN M30 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property PACKAGE_PIN P30 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]

set_property LOC GTXE2_CHANNEL_X0Y23 [get_cells {pcie_7x_top_aximm_i/pcie_7x_i/gt_wrapper_gtx/pipe_wrapper_i/gtxe2_channel_i}]
set_property LOC PCIE_X0Y0 [get_cells {pcie_7x_top_aximm_i/pcie_7x_i/pcie_block_inst/pcie_2_1_block}]

create_clock -name pcie_100mhz_refin -period 10 [get_nets pcie_7x_top_aximm_i/sys_clk]
create_clock -name pcie_125mhz_d_rxusr_oob_p -period 8 [get_nets pcie_7x_top_aximm_i/pcie_7x_i/in_module_mmcm.pipe_clock_i/clk_125mhz]
create_clock -name pcie_62d5mhz_user1_user2 -period 16 [get_nets pcie_7x_top_aximm_i/pcie_7x_i/in_module_mmcm.pipe_clock_i/userclk1]
}
close $xdc_fh

read_verilog -sv \
  $src_root/src/xilinx_pcie_mmcm.v \
  $src_root/src/axil_to_al.v \
  $src_root/src/axis_pcie_to_al_us.v \
  $src_root/src/pcie_7x.v \
  $src_root/src/pcie_axi_rx.v \
  $src_root/src/pcie_axi_tx.v \
  $src_root/src/pcie_block.v \
  $src_root/src/pcie_brams.v \
  $src_root/src/pcie_tx_thrtl_ctl.v \
  $src_root/src/pipe_wrapper_gtx.v \
  $top_overlay \
  $src_root/src/aximm-minimal/pcie_7x_top_aximm.v \
  $src_root/src/aximm-minimal/axil_minimum.v

read_xdc $xdc_overlay
synth_design -top pcie_7x_top_aximm_ypcb_480t -part xc7k480tffg1156-2
write_checkpoint -force $out_dir/post_synth.dcp
opt_design
place_design
write_checkpoint -force $out_dir/post_place.dcp
route_design
write_checkpoint -force $out_dir/post_route.dcp
report_timing_summary -file $out_dir/timing_summary.rpt
report_utilization -file $out_dir/utilization.rpt
write_bitstream -force $out_dir/ypcb_pcie_y26_lane0_oracle.bit
