#!/usr/bin/env python3
"""Generate a nextpnr --pre-place BEL lock script from extracted packed-cell BEL locks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a nextpnr Python pre-place BEL lock script."
    )
    parser.add_argument("--locks-json", required=True, type=Path)
    parser.add_argument("--out-py", required=True, type=Path)
    parser.add_argument(
        "--scope",
        action="append",
        default=[],
        help="Optional scope filter. Repeatable; keeps only matching lock scopes.",
    )
    parser.add_argument(
        "--type",
        action="append",
        default=[],
        help="Optional type filter. Repeatable; keeps only matching lock types.",
    )
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Generated hook warns instead of failing if a locked cell is absent.",
    )
    args = parser.parse_args()

    locks_doc = load_json(args.locks_json)
    requested_scopes = set(args.scope)
    requested_types = set(args.type)

    def keep_lock(lock: dict[str, Any]) -> bool:
        if str(lock.get("type", "")) == "BSCAN":
            return False
        if requested_scopes and str(lock.get("scope", "")) not in requested_scopes:
            return False
        if requested_types and str(lock.get("type", "")) not in requested_types:
            return False
        return True

    locks = [lock for lock in locks_doc["locks"] if keep_lock(lock)]
    allow_missing = "True" if args.allow_missing else "False"
    script = f'''# Generated by scripts/task6/generate_nextpnr_pre_place_bel_locks.py.
# Runs under nextpnr-xilinx --pre-place after packing and before placement.

LOCKS = {json.dumps(locks, indent=2, sort_keys=True)}
ALLOW_MISSING = {allow_missing}

applied = 0
missing = []
conflicts = []
used_cells = set()


def all_cell_names():
    try:
        return list(ctx.cells.keys())
    except AttributeError:
        names = []
        for item in ctx.cells:
            for attr in ("key", "first"):
                if hasattr(item, attr):
                    names.append(str(getattr(item, attr)))
                    break
            else:
                names.append(str(item[0]))
        return names


def first_unused(candidates):
    for cell_name in sorted(candidates):
        if cell_name in ctx.cells and cell_name not in used_cells:
            return cell_name
    return None


def alias_cell_names(name):
    aliases = [name, "rowstream_ddr3." + name]

    prefix_aliases = (
        ("ddr3_top_inst.ddr3_phy_inst.", "uberddr3.ddr3_phy_inst."),
        ("ddr3_top_inst.ddr3_controller_inst.", "uberddr3.ddr3_controller_inst."),
        ("ddr3_top_inst.", "uberddr3."),
    )
    for old_prefix, new_prefix in prefix_aliases:
        if name.startswith(old_prefix):
            aliases.append(new_prefix + name[len(old_prefix):])

    exact_aliases = {{
        "clk_wiz_inst.plle2_adv_inst": "clock_pll",
        "clk_wiz_inst.clkout1_buf": "clk100_90_bufg",
        "clk_wiz_inst.clkout2_buf": "clk100_bufg",
        "clk_wiz_inst.clkout3_buf": "clk200_bufg",
        "clk_wiz_inst.clkout4_buf": "clk25_bufg",
    }}
    if name in exact_aliases:
        aliases.append(exact_aliases[name])

    # Preserve order but avoid duplicate candidate work.
    seen = set()
    result = []
    for alias in aliases:
        if alias not in seen:
            seen.add(alias)
            result.append(alias)
    return result


def resolve_cell_name(lock):
    name = lock["cell"]
    aliases = alias_cell_names(name)
    direct = first_unused(aliases)
    if direct is not None:
        return direct

    cell_names = all_cell_names()

    # Standalone DDR lock manifests are captured without the combined wrapper
    # instance prefix.  Prefer deterministic suffix/prefix matches so the same
    # physical lock bundle can be reused under rowstream_ddr3 in the PCIe+DDR3
    # top without regenerating the baseline from scratch.
    suffix_candidates = [
        cell_name for cell_name in cell_names
        if (cell_name.endswith("." + name) or cell_name.endswith(name))
        and cell_name not in used_cells
    ]
    resolved = first_unused(suffix_candidates)
    if resolved is not None:
        return resolved

    # Yosys/nextpnr preserve the hierarchical reset-release signal name, but
    # the synthesized $LUT$ numeric suffix can move between builds. Treat the
    # pre-$LUT$ portion as the durable identity and assign same-prefix/suffix
    # locks in deterministic cell-name order.
    if "$LUT$" not in name:
        return None
    prefix = name.split("$LUT$", 1)[0] + "$LUT$"
    prefixes = []
    for alias in aliases:
        alias_prefix = alias.split("$LUT$", 1)[0] + "$LUT$"
        prefixes.append(alias_prefix)
    candidates = [
        cell_name for cell_name in cell_names
        if any(cell_name.startswith(pfx) or ("." + pfx) in cell_name for pfx in prefixes)
        and cell_name not in used_cells
    ]
    return first_unused(candidates)


for lock in LOCKS:
    name = resolve_cell_name(lock)
    bel = lock["bel"]
    if name is None:
        missing.append(lock)
        continue
    cell = ctx.cells[name]
    existing_bel = cell.attrs["BEL"] if "BEL" in cell.attrs else None
    if existing_bel is not None and str(existing_bel) != bel:
        conflicts.append({{
            "cell": name,
            "type": lock.get("type", ""),
            "old_bel": str(existing_bel),
            "new_bel": bel,
        }})
        continue
    cell.setAttr("BEL", bel)
    used_cells.add(name)
    applied += 1

if conflicts:
    raise RuntimeError("Task 6 pre-place BEL lock conflicts: " + repr(conflicts[:16]))
if missing and not ALLOW_MISSING:
    raise RuntimeError("Task 6 pre-place BEL lock missing cells: " + repr(missing[:16]))

print(
    "Task 6 pre-place BEL locks: applied={{}} missing={{}} source={args.locks_json}"
    .format(applied, len(missing))
)
'''
    args.out_py.write_text(script, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
