#!/usr/bin/env python3
"""Generate a nextpnr --pre-place BEL lock script from extracted packed-cell BEL locks."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a nextpnr Python pre-place BEL lock script."
    )
    parser.add_argument("--locks-json", required=True, type=Path)
    parser.add_argument("--out-py", required=True, type=Path)
    parser.add_argument(
        "--scope",
        action="append",
        default=[],
        help="Optional scope filter. Repeatable; keeps only matching lock scopes.",
    )
    parser.add_argument(
        "--type",
        action="append",
        default=[],
        help="Optional type filter. Repeatable; keeps only matching lock types.",
    )
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Generated hook warns instead of failing if a locked cell is absent.",
    )
    args = parser.parse_args()

    locks_doc = load_json(args.locks_json)
    requested_scopes = set(args.scope)
    requested_types = set(args.type)

    def keep_lock(lock: dict[str, Any]) -> bool:
        if requested_scopes and str(lock.get("scope", "")) not in requested_scopes:
            return False
        if requested_types and str(lock.get("type", "")) not in requested_types:
            return False
        return True

    locks = [lock for lock in locks_doc["locks"] if keep_lock(lock)]
    allow_missing = "True" if args.allow_missing else "False"
    script = f'''# Generated by scripts/task6/generate_nextpnr_pre_place_bel_locks.py.
# Runs under nextpnr-xilinx --pre-place after packing and before placement.

LOCKS = {json.dumps(locks, indent=2, sort_keys=True)}
ALLOW_MISSING = {allow_missing}

applied = 0
missing = []
conflicts = []
used_cells = set()


def resolve_cell_name(lock):
    name = lock["cell"]
    if name in ctx.cells and name not in used_cells:
        return name

    # Yosys/nextpnr preserve the hierarchical reset-release signal name, but
    # the synthesized $LUT$ numeric suffix can move between the standalone
    # UberDDR3 reference and the LLM2FPGA wrapper.  Treat the pre-$LUT$ portion
    # as the durable identity and assign same-prefix locks in deterministic
    # cell-name order.  This keeps the four-lock policy strict without baking in
    # wrapper-specific numeric suffixes.
    if "$LUT$" not in name:
        return None
    prefix = name.split("$LUT$", 1)[0] + "$LUT$"
    candidates = sorted(
        cell_name for cell_name in ctx.cells
        if cell_name.startswith(prefix) and cell_name not in used_cells
    )
    if not candidates:
        return None
    return candidates[0]


for lock in LOCKS:
    name = resolve_cell_name(lock)
    bel = lock["bel"]
    if name is None:
        missing.append(lock)
        continue
    cell = ctx.cells[name]
    existing_bel = cell.attrs["BEL"] if "BEL" in cell.attrs else None
    if existing_bel is not None and str(existing_bel) != bel:
        conflicts.append({{
            "cell": name,
            "type": lock.get("type", ""),
            "old_bel": str(existing_bel),
            "new_bel": bel,
        }})
        continue
    cell.setAttr("BEL", bel)
    used_cells.add(name)
    applied += 1

if conflicts:
    raise RuntimeError("Task 6 pre-place BEL lock conflicts: " + repr(conflicts[:16]))
if missing and not ALLOW_MISSING:
    raise RuntimeError("Task 6 pre-place BEL lock missing cells: " + repr(missing[:16]))

print(
    "Task 6 pre-place BEL locks: applied={{}} missing={{}} source={args.locks_json}"
    .format(applied, len(missing))
)
'''
    args.out_py.write_text(script, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
