#!/usr/bin/env python3
"""Generate placeholder SystemVerilog stubs for circt_fp_* extern modules.

This script parses `hw.module.extern @circt_fp_*` declarations from an MLIR file
and emits synthesizable placeholder modules that are structurally compatible
with Yosys ingestion. These stubs are NOT numerically equivalent to IEEE-754.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Port:
    direction: str  # "in" or "out"
    name: str
    ty: str
    width: int


def parse_width(ty: str) -> int:
    ty = ty.strip()
    m = re.fullmatch(r"[iu](\d+)", ty)
    if m:
        return int(m.group(1))
    m = re.fullmatch(r"f(\d+)", ty)
    if m:
        return int(m.group(1))
    if ty == "none":
        return 1
    # Fallback for unsupported/parametric types.
    return 1


def parse_port(spec: str) -> Port:
    spec = spec.strip()
    m = re.fullmatch(r"(in|out)\s+([%]?[A-Za-z_][\w$]*)\s*:\s*(.+)", spec)
    if not m:
        raise ValueError(f"cannot parse port spec: {spec}")
    direction = m.group(1)
    name = m.group(2).lstrip("%")
    ty = m.group(3).strip()
    return Port(direction, name, ty, parse_width(ty))


def render_logic_decl(p: Port) -> str:
    dir_kw = "input" if p.direction == "in" else "output"
    if p.width <= 1:
        return f"{dir_kw} logic {p.name}"
    return f"{dir_kw} logic [{p.width - 1}:0] {p.name}"


def widen_or_trunc_expr(in_name: str, in_w: int, out_w: int) -> str:
    if out_w <= 1:
        if in_w <= 1:
            return in_name
        return f"{in_name}[0]"
    if in_w == out_w:
        return in_name
    if in_w > out_w:
        return f"{in_name}[{out_w - 1}:0]"
    pad = out_w - in_w
    return f"{{{pad}'b0, {in_name}}}"


def render_module(name: str, ports: list[Port]) -> str:
    in_ports = [p for p in ports if p.direction == "in"]
    out_ports = [p for p in ports if p.direction == "out"]

    lines: list[str] = []
    lines.append(f"module {name}(")
    for idx, p in enumerate(ports):
        comma = "," if idx != len(ports) - 1 else ""
        lines.append(f"  {render_logic_decl(p)}{comma}")
    lines.append(");")

    if not out_ports:
        lines.append("endmodule")
        return "\n".join(lines)

    seed_in = in_ports[0] if in_ports else None
    for idx, outp in enumerate(out_ports):
        if seed_in is None:
            expr = f"{outp.width}'b0" if outp.width > 1 else "1'b0"
        else:
            expr = widen_or_trunc_expr(seed_in.name, seed_in.width, outp.width)
            if idx > 0 and outp.width > 1:
                expr = f"{expr} ^ {outp.width}'h{idx:x}"
        lines.append(f"  assign {outp.name} = {expr};")
    lines.append("endmodule")
    return "\n".join(lines)


def parse_externs(text: str) -> dict[str, list[Port]]:
    # Match a whole extern declaration line. Current CIRCT emits these as
    # single lines in HW-clean files.
    pat = re.compile(r"hw\.module\.extern\s+@([A-Za-z_]\w*)\((.*?)\)")
    modules: dict[str, list[Port]] = {}
    for m in pat.finditer(text):
        name = m.group(1)
        if not name.startswith("circt_fp_"):
            continue
        body = m.group(2).strip()
        ports: list[Port] = []
        if body:
            for entry in [x.strip() for x in body.split(",") if x.strip()]:
                ports.append(parse_port(entry))
        modules[name] = ports
    return modules


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(
            "usage: gen_fp_stubs_from_mlir.py <input-hw-clean-mlir> <output-sv>",
            file=sys.stderr,
        )
        return 2

    in_path = Path(argv[1])
    out_path = Path(argv[2])
    text = in_path.read_text(encoding="utf-8")
    modules = parse_externs(text)

    out: list[str] = []
    out.append("// AUTO-GENERATED FILE. DO NOT EDIT.")
    out.append("// Generated by scripts/pipeline/gen_fp_stubs_from_mlir.py")
    out.append("// Placeholder circt_fp_* implementations for structural synthesis flow.")
    out.append("// NOT numerically equivalent to IEEE-754 semantics.")
    out.append("")
    for name in sorted(modules):
        out.append(render_module(name, modules[name]))
        out.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
