# Generated by scripts/task6/write_ypcb_litedram_config.py
# Open LiteX IO skeleton for YPCB-00338-1P1 DDR3 CH0.
#
# This intentionally omits a ddram.dm Subsignal because the open CH0 UCF
# used for this gate does not expose DDR3 data-mask pins. LiteDRAM's S7
# PHY guards DM generation with hasattr(pads, "dm"), so the next gate is
# a custom LiteX target instantiation using these pads rather than the
# stock standalone YAML generator.

from litex.build.generic_platform import IOStandard, Pins, Subsignal


_io = [
    ("clk200", 0,
        Subsignal("p", Pins("AH27")),
        Subsignal("n", Pins("AH28")),
        IOStandard("LVDS")),
    ("cpu_reset", 0, Pins("R28"), IOStandard("LVCMOS18")),
    ("ddram", 0,
        Subsignal("a",       Pins("AK27 AN23 AL24 AK26 AH24 AH25 AL26 AJ24 AJ25 AM23 AL28 AL25 AM25 AK24 AM27")),
        Subsignal("ba",      Pins("AM26 AP24 AN28")),
        Subsignal("ras_n",   Pins("AJ29")),
        Subsignal("cas_n",   Pins("AP26")),
        Subsignal("we_n",    Pins("AN27")),
        Subsignal("cs_n",    Pins("AK28")),
        Subsignal("dq",      Pins("AG17 AG16 AH17 AJ19 AH18 AH19 AJ16 AJ17 AL20 AN17 AL19 AM16 AL18 AL16 AM20 AN18 AL23 AN20 AK23 AP19 AN22 AN19 AM22 AP20 AJ21 AH22 AK21 AG21 AG22 AG20 AH23 AG23 AJ32 AK32 AK31 AL30 AL34 AL31 AK34 AL29 AJ34 AH32 AJ30 AH34 AF31 AG30 AG31 AF30 AE32 AC33 AF33 AC32 AD34 AC34 AE33 AE31 AE26 AF29 AE24 AF28 AF24 AG25 AF26 AF25")),
        Subsignal("dqs_p",   Pins("AK16 AM17 AP21 AH20 AK33 AG33 AE34 AE27")),
        Subsignal("dqs_n",   Pins("AK17 AM18 AP22 AJ20 AL33 AH33 AF34 AE28")),
        Subsignal("clk_p",   Pins("AN25")),
        Subsignal("clk_n",   Pins("AP25")),
        Subsignal("cke",     Pins("AP27")),
        Subsignal("odt",     Pins("AK29")),
        Subsignal("reset_n", Pins("AD31")),
        IOStandard("SSTL15")),
]
